### ISSUE TITLE
modbus_client depends on collection ^1.17.2

### ISSUE THREAD

**Issue by magicmatt007** [cabbi/modbus_client#1]
First of all thanks for making this package available!

When I try to install it on a fresh Flutter app (Counter app), I get the following error message:

> because every version of flutter from sdk depends on collection 1.17.1 and every version of modbus_client depends on collection ^1.17.2, flutter from sdk is incompatible with modbus_client.
> So, because nfcapp_flutter depends on both flutter from sdk and modbus_client any, version solving failed.

Any ideas how to resolve this?

Thx!
Matthias

**Comment by aljaber** [comment]
I had same problem yesterday, I updated dependencies with
`flutter pub upgrade --major-versions`

and in pubspec.yml added

```
dependency_overrides:
  collection: ^1.17.2
```

**Comment by cabbi** [comment]
I gave a try and had same issue, so I will set collection to 1.17.1

modbus_client 1.0.1 is available, just call "flutter pub upgrade" and then you can add new modbus_client packages
