### ISSUE TITLE
Pass byteCount in constructor

### ISSUE THREAD

**Issue by jaka-shac** [cabbi/modbus_client#2]
Hello, first of all thank you for your great work and this awesome library.

I am playing around and try to read address which is as follows: 
<img width="1068" alt="Screenshot 2024-02-07 at 10 08 26" src="https://github.com/cabbi/modbus_client/assets/155944503/1bbe4ed5-d997-460e-ad6e-a418ddbf9d6b">
Turning the first part to decimal should be 154 for the address:
```
    ModbusUint16Register(
        name: "ConsumEnergyTodayInput",
        type: ModbusElementType.inputRegister,
        address: 154,
        onUpdate: (self) => print(self)),
```
but I am getting incorrect output. It seems that the problem lays in length of the address as it lays over 2 bytes. I tried to pass byteCount as a parameter but getting this error:
<img width="1343" alt="Screenshot 2024-02-07 at 9 35 48" src="https://github.com/cabbi/modbus_client/assets/155944503/1390c6eb-86cb-454c-9d15-a5dd4549b885">

Could you please advise how to read such address?

Thank you very much in advance.

**Comment by cabbi** [comment]
Hi, 

I don't think the problem is the 2 bytes length. The image you're showing tells its an uint16 (i.e. 2 bytes register).
Which is the error code you're getting?

The issue might be the element type: are you sure it's an inputRegister and not an holdingRegister.
 
BTW, you can leave the address in hex notation -> address: 0x9A,

**Comment by cabbi** [comment]
First picture is a element goup issue: it's too big
Second picture the register is a 1 byte element (at least, that's what I get from the address and the last number 1 on the right) 
Try add and use this class:

**Comment by cabbi** [comment]
Sorry, ignore the above comment and piece of code, by definition modbus registers are 2 bytes long.

Which server are you trying to connect to?
What is the number on the right of pictures you are providing?

**Comment by jaka-shac** [comment]
Thank you very much for you response.

The issue in the end was really just in the group request size. Just for my understanding. What is the limit for the group request?

Thank you for your support.

**Comment by cabbi** [comment]
The group ranges are defined by the Modbus specs:

**Comment by cabbi** [comment]
Please close the issue if this has been solved, thanks

**Comment by jaka-shac** [comment]
Thank you very much. Closing the issue.
