### ISSUE TITLE
Wrong Function Code Issue

### ISSUE THREAD

**Issue by mikucukyilmaz** [cabbi/modbus_client#4]
Hello, 
As we are testing with Modbus Slave Tool, reading holding register with the packets below returns 
ModbusResponseCode.requestRxWrongFunctionCode

Slave ID 0x14 and Function Code is 0x03 is correct but couldn't figure it out why it returns wrong function code. 
Tx: 14 03 00 06 00 01 66 CE
Rx: 14 03 02 0C 80 B1 27

Thanks.

**Comment by mikucukyilmaz** [comment]
In the section below,
 if (_rxData![1] != request.functionCode) {
      return ModbusResponseCode.requestRxWrongFunctionCode;
}
it gives error as below
The type of the right operand ('FunctionCode') isn't a subtype or a supertype of the left operand ('int').
Try changing one or both of the operands.

**Comment by cabbi** [comment]
Sorry for that, I think it's a bug I've introduced with new version 1.2.0
Will fix it asap

**Comment by mikucukyilmaz** [comment]
Thanks!
