### ISSUE TITLE
03 (0x03) Read Holding Registers & 16 (0x10) Write Multiple Registers

### ISSUE THREAD

**Issue by mikucukyilmaz** [cabbi/modbus_client#5]
Hello, 
As far as I see, reading and writing operations are limited with 16 and 32-bit datatypes.  
Modbus function codes 0x03 and 0x06 support writing and reading multiple bytes. I tried to add an implementation as below, but  I failed. What I am trying to achieve is modifying the sendWriteRequest and readRequest methods as they accept byte arrays with lengths of more than 4 bytes. 
I set the class with the byteCount required variable, and if byteCount > 4, it uses this write method. After this call, it says Modbus is not initiated. 
```

ModbusWriteRequest _getWriteRequestWithCustomByteLength(dynamic value, {bool rawValue = false, int? unitId, Duration? responseTimeout}) {
  if (type.writeMultipleFunction == null) {
    throw ModbusException(
      context: "ModbusElement",
      msg: "$type element does not support custom byte length write request!");
  }
  Uint8List uint8List = Uint8List.fromList(value);

  var pdu = Uint8List(7 + byteCount); // Adjust the PDU length according to custom byte length
  var byteData = ByteData.view(pdu.buffer);
  byteData.setUint8(0, type.writeMultipleFunction!.code);
  byteData.setUint16(1, address);
  byteData.setUint16(3, byteCount ~/ 2); // Register count
  byteData.setUint8(5, byteCount); // Byte count

  // Set value in the PDU
  for (int i = 0; i < byteCount - 2; i++) {
    // byteData.setUint8(6 + i, uint8List[i]);
    byteData.setUint8(6 + i, uint8List[i]);

    if (kDebugMode) {
      print(uint8List[i]);
    }
  }

  return ModbusWriteRequest(this, pdu, type.writeMultipleFunction!, unitId: unitId, responseTimeout: responseTimeout);
}
```

**Comment by cabbi** [comment]
I'm the way implementing a `ModbusBytesRegister` class that handles bytes array.
Need some time since this project is on my private spare time. I hope to release soon.

**Comment by cabbi** [comment]
Can you please check the new version on https://github.com/cabbi/modbus_client/tree/ModbusBytesRegister? 
If it is working for your needs I will update examples readme and so on.

**Comment by mikucukyilmaz** [comment]
I tested write and read byte methods. Everything works fine.

Thanks!

**Comment by cabbi** [comment]
New modbus_client version 1.2.1 has been released
